spring.application.name=SpringBoot_AI

server.port=8080

spring.ai.openai.api-key=${OPENAI_API_KEY}

#AI ??
spring.ai.openai.model=gpt-4o-mini

#??? ??
spring.ai.openai.embedding.options.model=text-embedding-3-small